name: 'Setup meshStack Authentication'
description: 'Authenticates with meshStack and stores authentication token'
inputs:
  base_url:
    description: 'The URL of the meshStack instance'
    required: true
    type: string
  client_id:
    description: 'The client ID for authentication'
    required: true
    type: string
  key_secret:
    description: 'The key secret for authentication'
    required: true
    type: string
outputs:
  token_file:
    description: 'Path to the file containing the authentication token'
runs:
  using: 'node24'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'


