name: Test Action
on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Meshstack Authentication
        id: setup-meshstack-auth
        uses: ./
        with:
          base_url: https://federation.dev.meshcloud.io
          client_id: ${{ secrets.CLIENT_ID }}
          key_secret: ${{ secrets.KEY_SECRET }}
